# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Shuffles each column of a numeric matrix
#'
#' @param mat matrix to shuffle
#' @return matrix in which all the columns are shuffled (each column is shuffled separately)
shuffle_each_column <- function(mat) {
    .Call(`_methylayer_shuffle_each_column`, mat)
}

